sonar.organization=shiva-shakti-it
sonar.projectKey=Shiva-Shakti-IT_project_poc_go_service
sonar.projectName=project_poc_go_service

sonar.sources=services

sonar.exclusions=**/Dockerfile

sonar.go.coverage.reportPaths=sonar-reports/user-coverage.out,sonar-reports/order-coverage.out